/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.doubango.utils;

import android.content.pm.PackageManager;

import com.sunkaisens.skdroid.sdk.NgnSKDroid;

public class AndroidUtils {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public AndroidUtils(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AndroidUtils obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() throws Throwable {
	  super.finalize();
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        utilsJNI.delete_AndroidUtils(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AndroidUtils() {
    this(utilsJNI.new_AndroidUtils(), true);
  }

  public static java.math.BigInteger getCpuFamily() {
    return utilsJNI.AndroidUtils_getCpuFamily();
  }

  public static java.math.BigInteger getCpuFeatures() {
    return utilsJNI.AndroidUtils_getCpuFeatures();
  }
  
  /**
   * 用户权限检测
   * @param permName 权限名称
   * @return 返回结果
   */
  public static boolean hasPermission(String permName){
	  boolean hasPerm = false;
	  PackageManager pm = NgnSKDroid.getInstence().getGlobleContext().getPackageManager();
	  
	  if(PackageManager.PERMISSION_GRANTED ==
			  pm.checkPermission(permName, "com.sunkaisens.skdroid")){
		  hasPerm = true;
	  }
	  
	  return hasPerm;
  }
  
  public static class PermissionSKD{
	  
	  public static final String READ_CONTACTS = 
			  "android.permission.READ_CONTACTS";
	  public static final String CAMERA = 
			  "android.permission.CAMERA";
	  public static final String RECORD_AUDIO =
			  "android.permission.RECORD_AUDIO";
	  public static final String MODIFY_AUDIO_SETTINGS = 
			  "android.permission.MODIFY_AUDIO_SETTINGS";
  }

}
